clone:
      tags: true

build:
  pretest:
    image: dock.pw.fr/pw/python:$$PYTHON_VERSION
    commands:
      - pip install -q -e . 
      - pip install -q flake8 coverage coverage-badge
      - echo "****** Tests de code *****"
      - flake8 setup.py lib/wgap_probe
  bundle:
    image: dock.pw.fr/pw/debpkg:$$DEBIAN_VERSION
    commands:
      - apt-get install -y dh-systemd python3-setuptools python3-yaml python3-colorlog
      - dpkg-buildpackage -b
      - fakeroot debian/rules clean
  test:
      image: dock.pw.fr/pw/wgap-probe:jessie
    privileged: true
    commands:
      - echo "****** Tests fonctionnels *****"
      - uname -a 
      - apt-get update >/dev/null
      - apt-get install python3-yaml python3-pkg-resources python-bcc kernel-common python3-colorlog python3-netaddr init-system-helpers
      - mv -f /etc/kernel-img.conf.ucf-new /etc/kernel-img.conf
        #      - apt-get install -o Dpkg::Options::="--force-confnew" -y linux-headers-`uname -r` linux-image-`uname -r`
      - dpkg -i ../*deb
      - dpkg -c ../wgap-probe*deb
      - sleep 2
      - mount -t debugfs debugfs /sys/kernel/debug
      - mount -t tracefs tracefs /sys/kernel/debug/tracing
      - echo "*** TEST DESACTIVES ***** /usr/bin/wgap-probe test"
      - /usr/bin/wgap-probe test

publish:
  sftp:
    host: pippin.planet-work.net
    username: pkg
    files:
      - ../*.deb
    destination_path: incoming/wgap/$$DEBIAN_VERSION
    when:
      event: tag
  ssh:
    host: pippin.planet-work.net
    user: pkg
    commands:
      - aptly repo add debian-$$DEBIAN_VERSION incoming/wgap/$$DEBIAN_VERSION && aptly publish update $$DEBIAN_VERSION debian 
    when:
      event: tag

matrix:
  PYTHON_VERSION:
    - 3.4
  DEBIAN_VERSION:
    - jessie
