# Runtime configuration for the wgap application.

# Installs kernel headers with apt : apt-get install -y linux-headers-`uname -r` linux-image-`uname -r`
autoinstall_headers: True

loglevel: WARNING

# polling interval (seconds)
poll_interval: 1

input:
    - file_write
    - tcp_connect
    - inet_listen
    - execve

filter:
    uid_min: 1000
    gid_min: 1000
    include_files:
        - '*.php'
    exclude_users:
        - planet-work
        - test-cluster2
    exclude_files:
        - "*/cache/data_cron.lock_check.php"
        - "*/cache/sql_*php"
        - "*/debian-*/tmp/*"
        - "*/tmp/meta_cache.php"
        - "*/cache/class_index.php"
        - "*/wp-content/cache/db/*"
        - "*/cache/cbtpl/*"
        - "*/cache/com_*/*"
        - "*/cache/mod_*/*"
        - "*/cache/_system/*"
        - "*/cache/smarty/cache/*" 
        - "*/cache/sh404sef_rconfig/*"
        - "*/wp-content/wflogs/ips.php"
        - "*/wp-content/wflogs/config.php"
        - "*/wp-content/wflogs/attack-data.php"
        - "*/logs/error.php"
        - "*/plugins/wordfence/tmp/configCache.php"
        - "*/ecrire/data/meta_cache.php"
        - "*/backwpup-working.php"
        - "*/wp-content/cache/object/*"
        - "*/wp-content/plugins/si-captcha-for-wordpress/captcha/cache/*"
        - "*/wp-content/uploads/sucuri/sucuri-*failedlogins.php"
        - "*/assets/cache/*pageCache.php"
        - "*/wp-content/uploads/fusion-builder-avada-pages/*"
        - "*.cache.php"
    exclude_ports:
        - 3306
        - 6379
    exclude_progs:
        - /bin/sh
        - /usr/sbin/sendmail
        - nullmailer-inject
        - /etc/apache2/conf/sendmail-secure
        - /usr/sbin//nullmailer-queue
        - /bin/ls
        - /usr/bin/which
        - /usr/bin/convert
   
callbacks:
    - pms_php:
        - include: "*.php"
        - function: check_pms

output:
    heka:
        address: 10.3.1.250:6201
    collector:
        address: 10.3.1.251:6201
        format: json
#    console:
#        format: text


