# Runtime configuration for the wgap application.

# Installs kernel headers with apt : apt-get install -y linux-headers-`uname -r` linux-image-`uname -r`
autoinstall_headers: True

loglevel: DEBUG

# polling interval (seconds)
poll_interval: 1

input:
    - file_write
    - tcp_connect
    - tcp_listen

filter:
    uid_min: 1000
    gid_min: 1000
    include_files:
        - '*.php'
    exclude_users:
        - planet-work
        - test-cluster2
    exclude_files:
        - "*/cache/*"
        - "*/debian-*/tmp/*"
        - "/tmp/*"
        - "/var/lib/tmp/*"
        - "*/sent-mails/*"
        - "*/cache/smarty/cache/*"
        - "*/wp-content/wflogs/ips.php"
        - "*/wp-content/wflogs/config.php"
        - "*/wp-content/wflogs/attack-data.php"
        - "*/logs/error.php"
        - "*/wp-content/cache/*"
        - "*/plugins/wordfence/tmp/configCache.php"
    exclude_ports:
        - 3306
   
callbacks:
    - pms_php:
        - include: "*.php"
        - function: check_pms

output:
    collector:
        address: 10.3.1.251:6201
        format: json
    console:
        format: text


