# Runtime configuration for the wgap application.

input:
    - file_write
    - file_read
    - tcp_connect
    - tcp_listen

filter:
    uid_min: 1000
    gid_min: 1000
    exclude_users:
        - planet-work
        - test-cluster2
    exclude_paths:
        - "*/cache/"
    exclude_files:
        - access.log
        - error.log
        - processes.log
        - other_vhosts_access.log
    exclude_ports:
        - 3306
   
callbacks:
    - pms_php:
        - include: "*.php"
        - function: check_pms

output:
    - collector:
        address: 127.0.0.1:6201
        format: json
    - console


